name: Docker Image Delivery

on:
  workflow_dispatch:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # 이미지 태그 설정
      - name: Set Tag
        run: echo "TAG=$(data +%s)-ci" >> "$GITHUB_OUTPUT"
      # Docker Build 진행
      - name: Build the Docker Image
        env:
          TAG: ${{ steps.image-tag.outputs.TAG }}